
name: Dennis D. Carreira

# Title for your site as it will appear in google
# e.g. Resume, Curriculum Vitae, Work History
title: Resume for Dennis D. Carreira

# SEO description
description: Digital resume for Dennis D. Carreira, developer and engineer in Lisbon.

# URL of this resume
url: ''


# these should be pretty self-explanatory :-P
email: dnns.carreira@gmail.com